spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_guild?characterEncoding=utf8
    username: root
    password: r@@t

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: false
    hibernate.ddl-auto: none

  liquibase:
    enabled: false
    #change-log: classpath:db/changelog/db.changelog-master.yaml